name: deb-package

on:
  push:
    tags:
      - '*'
    branches:
      - master
  workflow_dispatch:
jobs:
  build:
    #if: ${{ github.repository == 'rm-controls/rm_control' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ros-tooling/setup-ros@v0.2
        with:
          required-ros-distributions: noetic
      - name: Package deb
        uses: gdut-dynamic-x/ros-build-deb-action@v1
        with:
          ros_distro: noetic
          timestamp: true
      - name: Upload deb package to source
        if: ${{ github.repository == 'rm-controls/rm_control' }}
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SOURCE_SSH_HOST }}
          username: ${{ secrets.SOURCE_SSH_NAME }}
          key: ${{ secrets.SOURCE_SSH_KEYGEN }}
          source: "*.deb"
          target: "/usr/local/web/rm-source/ubuntu/incoming/"
      - name: Deploy deb package to source
        if: ${{ github.repository == 'rm-controls/rm_control' }}
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SOURCE_SSH_HOST }}
          username: ${{ secrets.SOURCE_SSH_NAME }}
          key: ${{ secrets.SOURCE_SSH_KEYGEN }}
          script: |
                  cd /usr/local/web/rm-source/ubuntu/incoming/
                  reprepro  -s  -b  /usr/local/web/rm-source/ubuntu/  --waitforlock  1000  includedeb focal /usr/local/web/rm-source/ubuntu/incoming/*.deb && \
                  rm -f *.deb
