
name: ros-build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ros-tooling/setup-ros@v0.2
        with:
          required-ros-distributions: noetic
      - uses: ros-tooling/action-ros-ci@v0.2
        with:
          target-ros1-distro: noetic
      - name: Package deb
        run: |
          ls
          source /opt/ros/noetic/setup.bash
          sudo apt-get install python3-bloom fakeroot dh-make
          sudo bash -c 'echo "yaml file://`pwd`/rosdep.yaml" > /etc/ros/rosdep/sources.list.d/rm_control.list'
          rosdep update
          for file in rm_msgs rm_description
          do
            if test -d $file
            then
              echo "Trying to package $file"
              ls
              cd $file
              bloom-generate rosdebian --os-name ubuntu --ros-distro noetic
              fakeroot debian/rules binary
              cd ..
              newpackage=`ls -t | head -n 1`
              sudo dpkg -i $newpackage
            fi
          done
          for file in rm_common rm_dbus rm_gazebo rm_hw
          do
            if test -d $file
            then
              echo "Trying to package $file"
              ls
              cd $file
              bloom-generate rosdebian --os-name ubuntu --ros-distro noetic
              fakeroot debian/rules binary
              cd ..
              for newpack in `ls -t | head -n 2 | tac`
              do
                sudo dpkg -i $newpack
              done
            fi
          done
          for file in rm_control
          do
            if test -d $file
            then
              echo "Trying to package $file"
              ls
              cd $file
              bloom-generate rosdebian --os-name ubuntu --ros-distro noetic
              fakeroot debian/rules binary
              cd ..
            fi
          done
          ls
      - name: deploy file
        uses: wlixcc/SFTP-Deploy-Action@v1.0
        with:
          username: 'root'
          server: '${{ secrets.REPO_URL }} '
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }} 
          local_path: './*.deb'
          remote_path: '/usr/local/web/rm-source/incoming'
          args: '-o ConnectTimeout=5'
